language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_deploy:
    - cd app/build/outputs/apk/
before_install:
  - yes | sdkmanager "platforms;android-29"

script:
   - ./gradlew clean build --stacktrace
jdk:
  - oraclejdk8

deploy:
  provider: releases
  file: Covid-19.apk
  skip_cleanup: true

  on:
    repo: daisukikancolle/Corona
    all_branches: true
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "AAAAB3NzaC1yc2EAAAADAQABAAACAQCtq9sf/vCf6q8OQnMgwD+GAhU4rhQVZ44THMGGFxyWCt3j9oxjHAOzmT8U6EobdKuzhWgjSCl7g7H79y565SLd4hOIIM1X6GX71A+zVqdJ1BTnsAHv1aiNPcpKXBj4nFfdiZp1INmFT8bt5W9mxXmw53z6eO/nEiCZUEIOeu+8vHii5TTk4cmPxLZTOcRewMaQChfUn5SxkjCfJymZYissbnzaYobiKjbETd0kLJ1sQCMCYJpelEhdSBbD34oiW+d1+UjRo/aP/fMtRwPGglwuX9r1MVIEzylxJtIAFWyh/+fyDQJFKNlPpjHTu706su0FD0mIzsUTgJKNTWQ2oJ1TrgNr7ed2iupfjNzwyeSDK8xCb7AdAtYusy8AXHI8Bukd2Y+6MI3pVNA6am++q/9TcObmIhqsQwLfqsMp5Dv2cjhhURLog3u/5c3PrdwqN7OPqpfXuQ1jDYifRgdYITubtUKyqiFG1m0E73z8EMybjuM+tqdopafWjXI/gGu/Ur7bfqpkuDUJc5eK9Wvu1J3+fNIuL66iE/tYZi9THGK8OTE65GaXsipO12KCGiXvFifpz5lVoPrHHadAGEThjbH3BU0ZpjtouKExbOnwmp63WNw9T3Zi0sn+YOVYB6RtkAmvgDlVDrVcDJW9xT7kNguiBkwurVkzjVwrBZq1R9HX1w== "
