language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_deploy:
    - cp $TRAVIS_BUILD_DIR/.keystore $HOME
    - cd app/build/outputs/apk/
before_install:
  - yes | sdkmanager "platforms;android-29"

script:
   - ./gradlew clean build --stacktrace
jdk:
  - oraclejdk8

